<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * taskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class taskRepository extends EntityRepository
{
   public function findTaskByDate($date)
   {
       $tasks = $this->getEntityManager()->createQuery(
           "SELECT t FROM AppBundle:Task t WHERE t.start LIKE :date"
       )->setParameter("date", $date)->getResult();

       return $tasks;
   }

}
